### ISSUE TITLE
Enabling and disabling sharing and / or embeding button.

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona-organizations#13]
# This is a Feature Proposal

#### :tophat: Description

Processes on an organization could be private (for members only).
That is why we should be able to activate and deactivate options for sharing or embeding elements.

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by zuzust** [comment]
There are two use cases regarding restricted access:

1. Access to the platform is only allowed to a group of users (see #8), so that an organization's activity is only visible to its members.
2. Private processes or assemblies accessible by invitation only (see decidim/decidim#2282), so that only selected users can see them and participate in their activities.

Either way, it should be taken into account that sharing or embedding contents should be disabled in those scenarios by default.

**Comment by zuzust** [comment]
After reasoning about this for a while, it seems to be more a business rule than an opt-in feature. Follow #8 and decidim/decidim#2282 for further discussion on the issue.

Closing this.
